import Head from 'next/head';


import {  Layout , Services, Mainmenu,Body, Hero , Aboutus , 
  MyAnimatedTypo, SelectItem,About, slider, Newsletter, Built , Menu } 
  from '../components';

import {Heading} from "../smallsections";

import { client } from "../lib/client";
import { useStore } from"../../store/store"; 






export default function Home({pizzas}) {


  return (

    <>
    <Layout>
      <div   className="overflow-hidden ">
        <Head>
          <title>FoodVilla</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="http://localhost:3001/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FPizzaMom.0c113a46.png&w=1080&q=75" />
        </Head>


        {/* body */}
        <main  >
        
        <div className="relative overflow-hidden mx-2">
        <div className="gradient-05" />
        <Hero/>
        <div className="gradient-04" />
         <Services/>
        </div>
        
        <div className="relative">
        <Mainmenu  />
        <div className="gradient-02  z-0" />
         <Menu pizzas={pizzas} />
         <Heading/>

         <div  className="relative " >
          <Body/>
         <div className="gradient-03  z-0" />
         </div>
      
        <About />
        
        <SelectItem/>
        </div>
        
        
        </main>
        
        <div  className="relative " >
             <Aboutus/>
        <div className="gradient-03  z-0" />
             <Newsletter/>
        </div>   
        <Built/>
        <MyAnimatedTypo/>
        
        </div>
        </Layout>
        

        </>
        );
      }
      
      
      
      
      
      
export const getServerSideProps = async()=>{
  const query = '*[_type == "pizza"]';
  const pizzas = await client.fetch(query);
  return {
    props:{
      pizzas
    }
  }
}
    

   






















// import React,{useState} from 'react';
// import Image from 'next/image';
// import {useStore} from"../../store/store"
// import Link from 'next/Link';
// import close from '../assets/close.png';
// import menu from '../assets/menu.png';
// import {UilShoppingBag} from '@iconscout/react-unicons' ;
// import Darkmode from './../components/Darkmode';
// import { navLinks } from "../constants";

 

// export default function Header ()  {


// const menu = "https://cdn-icons-png.flaticon.com/512/2099/2099153.png";
//  const close = "https://cdn-icons-png.flaticon.com/512/2099/2099153.png"



//   const [active, setActive] = useState("Home");
//   const [toggle, setToggle] = useState(false);


// const title= "FoodVilla"

//   return (

//     <>

//     <div className="justify-between px-[.3rem]
//      sm:px-[3rem] flex items-center shadow-xl  dark:shadow-blue-500
//       shadow-orange-200 h-20 " >

//        <div className="Log flex flex-1 items-center  ">
//         <span className="bg-orange-600 flex   rounded-full ml-2
//          font-extrabold text-[1.5rem]  px-3  ">F</span>
//        <span className="text-xl text-black dark:text-white md:text-3xl font-bold">
//         {title}</span>
//        </div>   


       
//        <ul className="items-center  justify-center 
//        font-semibold transition-allflex-1 hidden sm:flex gap-10 ">
//         <a href="/"> <li  className=" dark:text-blue-500  text-xl 
//          hover:text-white cursor-pointer " >Home</li></a>

//         <Link href="/menu">
//         <li className=" hover:text-white  dark:text-blue-500  text-xl
//           cursor-pointer " >Menu</li>
//         </Link>
//         <Link href="/contactus">
//         <li className=" hover:text-white  dark:text-blue-500  text-xl
//           cursor-pointer " >Contact US</li>
//         </Link>

 
//        </ul>
       
        
      
//        <div className="class items-center gap-4 
//         flex justify-end mr-8 flex-end  flex-1 ">


//         <Darkmode/>
            
      



//            <Link  href="/cart" >
//             <div className="Cart">
//                   <div className="badge items-center relative flex z-99">
//                   <UilShoppingBag  size={40}/>
//                     <div className="absolute justify-center text-center
//                      items-center dark:bg-slate-500 bg-slate-400 rounded-full 
//                     flex p-1 h-[25px] bottom-5 -right-[.4rem] w-[25px]"> 1</div>
                  
//                   </div>
            
//             </div>
//            </Link>

          
//            <div className="ButtonIcons flex  ml-4  sm:hidden ">
//            <img className="w-[1.9rem]" 
//            src="https://cdn-icons-png.flaticon.com/512/2099/2099153.png" alt="" />
//           </div>


//        </div>
       

//     </div>



    
//          {/*Mobile Menu*/}


         
//          <div className="sm:hidden flex flex-1 justify-end items-center">
//          <img
//            src={toggle ? close : menu}
//            alt="menu"
//            className="w-[28px] h-[28px] object-contain"
//            onClick={() => setToggle(!toggle)}
//          />
 
//          <div
//            className={`${
//              !toggle ? "hidden" : "flex"
//            } p-6 bg-black-gradient absolute top-20 right-0 mx-4 my-2 min-w-[140px] rounded-xl sidebar`}
//          >
//            <ul className="list-none flex justify-end items-start flex-1 flex-col">
//              {navLinks.map((nav, index) => (
//                <li
//                  key={nav.id}
//                  className={`font-poppins font-medium cursor-pointer text-[16px] ${
//                    active === nav.title ? "text-white" : "text-dimWhite"
//                  } ${index === navLinks.length - 1 ? "mb-0" : "mb-4"}`}
//                  onClick={() => setActive(nav.title)}
//                >
//                  <a href={`#${nav.id}`}>{nav.title}</a>
//                </li>
//              ))}
//            </ul>
//          </div>
//        </div>

//     </>

//   )
// } 




// export default Header;